on:
  workflow_call:
    inputs:
      commit_hash:
        type: string
        description: 'Commit hash to deploy (Optional)'
        default: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          ref: ${{ inputs.commit_hash }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      
      - name: Format code
        run: npm run format
      - name: Run linter
        run: npm run lint

      - name: Start database
        run: npm run db:start
      - name: Wait for database to be ready
        run: sleep 20
      - name: Apply migrations to database
        run: npx prisma migrate deploy
      - name: Run tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Shutdown database
        run: npm run db:stop