name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get tag version
        id: tag_version
        run: echo ::set-output name=version::v$(jq -r '.version' package.json)

      - name: Create release tag ${{ steps.tag_version.outputs.version }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.tag_version.outputs.version }}',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ steps.tag_version.outputs.version }}',
                sha: context.sha
              });
            })

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: '.,!.github'
          target: ${{ secrets.DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data

      - name: SSH to server & Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: DEPLOY_DIRECTORY,ENV_FILE
          script: |
            echo "***DEPLOYER***: Change to deploy directory..."
            cd $DEPLOY_DIRECTORY

            echo '***DEPLOYER*** Override .env file'
            echo -e "$ENV_FILE" > .env

            echo '***DEPLOYER*** Install dependencies'
            npm install

            echo '***DEPLOYER*** Build code'
            npm run build

            echo '***DEPLOYER*** Apply migrations to database'
            npx prisma migrate deploy

            echo "***DEPLOYER*** Delete running app"
            npm run delete:prod

            echo '***DEPLOYER*** Running app'
            npm run start:prod
